name: Build and Push Docker Images

on:
  push:
    branches:
      - main
      - dev

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Backend Image
        run: |
          docker build -t ghcr.io/${{ github.repository }}/backend:latest -f backend/Dockerfile ./backend
          docker push ghcr.io/${{ github.repository }}/backend:latest

      - name: Build and Push Frontend Image
        run: |
          docker build -t ghcr.io/${{ github.repository }}/frontend:latest -f frontend/Dockerfile ./frontend
          docker push ghcr.io/${{ github.repository }}/frontend:latest
